#Define your project's libraries and source files here.
#This section is compulsory.
Libraries:
    #The name of the library.
    - name: work
    #The paths where the source files for this library can be found. Use "**" to match arbitrarily nested directories.
      paths:
        - "./src/**/*.vhd"
        - "./src/**/*.vhdl"


    - name: std
      paths:
        - "./lib/vhdl_libraries/**/*.vhd"
        - "./lib/vhdl_libraries/**/*.vhdl"


    - name: ieee
      paths:
        - "./lib/ieee2008/**/*.vhd"
        - "./lib/ieee2008/**/*.vhdl"


    - name: bitvis_irqc
      paths:
        - "./lib/UVVM/bitvis_irqc/src/*.vhd"
        - "./lib/UVVM/bitvis_irqc/src/*.vhdl"

    - name: bitvis_uart
      paths:
        - "./lib/UVVM/bitvis_uart/src/*.vhd"
        - "./lib/UVVM/bitvis_uart/src/*.vhdl"

    - name: bitvis_vip_avalon_mm
      paths:
        - "./lib/UVVM/bitvis_vip_avalon_mm/src/*.vhd"
        - "./lib/UVVM/bitvis_vip_avalon_mm/src/*.vhdl"

    - name: bitvis_vip_axilite
      paths:
        - "./lib/UVVM/bitvis_vip_axilite/src/*.vhd"
        - "./lib/UVVM/bitvis_vip_axilite/src/*.vhdl"

    - name: bitvis_vip_axistream
      paths:
        - "./lib/UVVM/bitvis_vip_axistream/src/*.vhd"
        - "./lib/UVVM/bitvis_vip_axistream/src/*.vhdl"

    - name: bitvis_vip_clock_generator
      paths:
        - "./lib/UVVM/bitvis_vip_clock_generator/src/*.vhd"
        - "./lib/UVVM/bitvis_vip_clock_generator/src/*.vhdl"

    - name: bitvis_vip_gpio
      paths:
        - "./lib/UVVM/bitvis_vip_gpio/src/*.vhd"
        - "./lib/UVVM/bitvis_vip_gpio/src/*.vhdl"

    - name: bitvis_vip_i2c
      paths:
        - "./lib/UVVM/bitvis_vip_i2c/src/*.vhd"
        - "./lib/UVVM/bitvis_vip_i2c/src/*.vhdl"

    - name: bitvis_vip_sbi
      paths:
        - "./lib/UVVM/bitvis_vip_sbi/src/*.vhd"
        - "./lib/UVVM/bitvis_vip_sbi/src/*.vhdl"

    - name: bitvis_vip_scoreboard
      paths:
        - "./lib/UVVM/bitvis_vip_scoreboard/src/*.vhd"
        - "./lib/UVVM/bitvis_vip_scoreboard/src/*.vhdl"

    - name: bitvis_vip_spi
      paths:
        - "./lib/UVVM/bitvis_vip_spi/src/*.vhd"
        - "./lib/UVVM/bitvis_vip_spi/src/*.vhdl"

    - name: bitvis_vip_uart
      paths:
        - "./lib/UVVM/bitvis_vip_uart/src/*.vhd"
        - "./lib/UVVM/bitvis_vip_uart/src/*.vhdl"

    - name: uvvm_util
      paths:
        - "./lib/UVVM/uvvm_util/src/*.vhd"
        - "./lib/UVVM/uvvm_util/src/*.vhdl"

    - name: uvvm_vvc_framework
      paths:
        - "./lib/UVVM/uvvm_vvc_framework/src/*.vhd"
        - "./lib/UVVM/uvvm_vvc_framework/src/*.vhdl"


#Enable/disable typechecking
TypeCheck: True


#Enable/disable check-as-you-type
CheckOnChange: True


#Linter rule configuration.
#Rules can be enabled or disabled.
#Rules also have a severity. It may be one of Info, Warning, Critical or Error.
Lint:
    #Threshold, below which messages are not displayed.
    Threshold: Warning


    #Long form rule configuration. Both enabled/disabled status and severity can be configured this way.
    DeclaredNotAssigned:
        enabled:  True
        severity: Warning #Default severity Warning


    #Short form. Only enabled/disabled status can be specified. Severity is the default for the rule.
    DeclaredNotRead:             True #Default severity Warning
    ReadNotAssigned:             True #Default severity Critical
    SensitivityListCheck:        True #Default severity Warning
    ExtraSensitivityListCheck:   True #Default severity Warning
    DuplicateSensitivity:        True #Default severity Warning
    LatchCheck:                  True #Default severity Critical
    VariableNotRead:             True #Default severity Warning
    # VariableNotWritten:          True #Default severity Warning
    PortNotRead:                 True #Default severity Warning
    PortNotWritten:              True #Default severity Critical
    NoPrimaryUnit:               True #Default severity Warning
    DuplicateLibraryImport:      True #Default severity Warning
    DuplicatePackageUsage:       True #Default severity Warning
    DeprecatedPackages:          True #Default severity Warning
    ImplicitLibraries:           True #Default severity Warning
    DisconnectedPorts:           True #Default severity Critical
