# [option]
# exclude_paths = {"./ip/.*"}

[rules]
# non_ansi_rules = true
wire_reg = true
case_default = true
enum_with_type = true
for_with_begin = true
if_with_begin = true
function_same_as_system_function = true
function_with_automatic = true
generate_for_with_label = true
generate_if_with_label = true
generate_keyword = true
genvar_declaration = true
loop_variable_declaration = true
inout_with_tri = true
interface_port_with_modport = true
legacy_always = true
level_sensitive_always = true
parameter_in_package = true
priority_keyword = true
unique0_keyword = true
unique_keyword = true
tab_character = true
