;(("default" . ((user-emacs-directory . "~/.emacs.d")))
(("default" . ((user-emacs-directory . "~/.spacemacs.d")
		 (server-name . "spacemacs")
		 (custom-file . "~/.config/spacemacs/custom.el")
		 (env . (("SPACEMACSDIR" . "~/.config/spacemacs")))
		      ))
 ("doom" . ((user-emacs-directory . "~/doom_install")
	    (server-name . "doom-emacs")
	    (env . (("DOOMDIR" . "~/.config/doom"))))
  	        ))
